name: device_screen_recorder_new
description: A Flutter plugin for record the screen. This plug-in requires Android SDK 21+ and iOS 10+
version: 0.0.6
homepage: https://github.com/nurshat13/device_screen_recorder_new-0.0.4
repository: https://github.com/nurshat13/device_screen_recorder_new-0.0.4
publisher: nurshat.org

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pigeon: ^10.1.5

flutter:
  plugin:
    platforms:
      android:
        package: ru.kovardin.device_screen_recorder_new
        pluginClass: DeviceScreenRecorderPlugin

